# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('battleadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashtag',
            old_name='tweet_text',
            new_name='hashtag_text',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='battle',
        ),
        migrations.AddField(
            model_name='battle',
            name='hashtag_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hashtag_2', to='battleadmin.Hashtag'),
        ),
    ]
