# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battleadmin', '0002_auto_20160410_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='battle',
            name='hashtag_2',
        ),
    ]
