# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 21:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battleadmin', '0004_auto_20160410_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='battle',
            old_name='hashtag_1',
            new_name='h1',
        ),
        migrations.RenameField(
            model_name='battle',
            old_name='hashtag_2',
            new_name='h2',
        ),
        migrations.RenameField(
            model_name='hashtag',
            old_name='hashtag_text',
            new_name='tag',
        ),
    ]
