# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-11 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battleadmin', '0005_auto_20160410_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='winner',
            field=models.CharField(default='Draw', max_length=140),
        ),
    ]
